import asyncio
import json
import logging
import os
import re
import shutil
import socket
import tempfile
import time
import uuid
from pathlib import Path
from urllib import error, request

from langchain_core.callbacks.manager import adispatch_custom_event

from ..state import VibeDeployState
from ..tools.digitalocean import (
    build_app_spec,
    delete_app,
    deploy_to_digitalocean,
    get_deploy_error_logs,
    list_apps,
    redeploy_app,
    wait_for_deployment,
)
from ..tools.github import create_github_repo, get_ci_failure_logs, push_files, wait_for_ci

logger = logging.getLogger(__name__)
_DO_APP_LIMIT_ERROR_SNIPPET = "app count"


def _use_local_deploy_mode() -> bool:
    return os.getenv("VIBEDEPLOY_DEPLOY_MODE", "").strip().lower() in {"local", "offline"}


async def _emit_runtime_event(
    event_name: str,
    *,
    config,
    node: str,
    phase: str,
    message: str,
    **extra,
) -> None:
    if config is None:
        return
    payload = {
        "type": event_name,
        "node": node,
        "stage": node,
        "phase": phase,
        "message": message,
        **extra,
    }
    await adispatch_custom_event(event_name, payload, config=config)


async def _emit_step_start(node: str, message: str, *, config, **extra) -> None:
    await _emit_runtime_event("deploy.step.start", config=config, node=node, phase=node, message=message, **extra)


async def _emit_step_complete(node: str, message: str, *, config, **extra) -> None:
    await _emit_runtime_event("deploy.step.complete", config=config, node=node, phase=node, message=message, **extra)


async def _emit_step_error(node: str, message: str, *, config, **extra) -> None:
    await _emit_runtime_event("deploy.step.error", config=config, node=node, phase=node, message=message, **extra)


async def deployer(state: VibeDeployState, config=None) -> dict:
    frontend_code = state.get("frontend_code", {}) or {}
    backend_code = state.get("backend_code", {}) or {}
    blueprint = state.get("blueprint", {}) or {}
    code_eval_result = state.get("code_eval_result", {}) or {}
    idea = state.get("idea", {}) or {}
    selected_flagship = str(state.get("selected_flagship") or idea.get("selected_flagship") or "").strip()

    build_validation = state.get("build_validation") or {}
    deploy_gate_result = state.get("deploy_gate_result") or {}
    app_name = str(blueprint.get("app_name") or "").strip() or _build_repo_name(idea)
    description = idea.get("tagline") or idea.get("problem") or "Generated by vibeDeploy"
    deploy_blocker = _get_deploy_blocker(
        frontend_code,
        backend_code,
        blueprint,
        code_eval_result,
        selected_flagship,
        build_validation,
        deploy_gate_result,
    )
    if deploy_blocker:
        logger.error("[DEPLOYER] Generated code incomplete; skipping deployment: %s", deploy_blocker)
        await _emit_step_error(
            "git_push", f"Skipping deployment: {deploy_blocker}", config=config, error=deploy_blocker
        )
        return {
            "deploy_result": {
                "app_id": "",
                "live_url": "",
                "github_repo": "",
                "status": f"code_incomplete: {deploy_blocker}",
            },
            "phase": "deployment_skipped",
            "error": deploy_blocker,
        }

    all_files = _merge_files(frontend_code, backend_code)
    has_frontend = any(k.startswith("web/") for k in all_files)

    frontend_file_count = len(frontend_code)
    backend_file_count = len(backend_code)
    logger.info(
        "[DEPLOYER] File counts — frontend: %d, backend: %d, merged: %d, has_frontend: %s",
        frontend_file_count,
        backend_file_count,
        len(all_files),
        has_frontend,
    )

    if not has_frontend and backend_file_count > 0:
        logger.warning(
            "[DEPLOYER] Frontend code is empty — deploying backend-only. "
            "Ensuring backend has a landing page at root URL."
        )
        if "main.py" in all_files and '@app.get("/")' not in all_files.get("main.py", ""):
            all_files["main.py"] = _inject_landing_page(all_files["main.py"], idea)
            logger.info("[DEPLOYER] Injected HTML landing page into main.py")

    all_files = _ensure_unique_backend_table_prefix(all_files, app_name)
    all_files = await _prepare_files_for_push(all_files)

    all_files.update(
        {
            "README.md": _generate_readme(idea, state.get("scoring") or {}, backend_code),
            ".github/workflows/ci.yml": _generate_ci_yml(has_frontend=has_frontend),
            ".env.example": _generate_env_example(),
        }
    )

    if _use_local_deploy_mode():
        await _emit_step_complete("git_push", "Local deploy mode enabled: skipping GitHub/DO deploy", config=config)
        result = await _local_fallback_deploy(app_name, all_files, "", "local_mode")
        result["deploy_result"].update({"ci_status": "skipped", "ci_url": "", "ci_repair_attempts": 0})
        return result

    github_org = os.getenv("GITHUB_ORG")
    await _emit_step_start("git_push", "Creating repository and pushing generated files", config=config)

    github_result = await create_github_repo(
        name=app_name,
        files=all_files,
        description=description,
        org=github_org or None,
    )

    github_repo_url = github_result.get("url", "")
    github_clone_url = github_result.get("clone_url", "")
    github_full_name = github_result.get("full_name", "")

    if github_result.get("status") == "error" or not github_clone_url:
        error_message = github_result.get("error", "GitHub repository creation failed")
        await _emit_step_error("git_push", f"GitHub push failed: {error_message}", config=config, error=error_message)
        if "GITHUB_TOKEN not set" in error_message:
            result = await _local_fallback_deploy(app_name, all_files, github_repo_url, "github_token_missing")
            return result
        return {
            "deploy_result": {
                "app_id": "",
                "live_url": "",
                "github_repo": github_repo_url,
                "status": f"github_error: {error_message}",
            },
            "phase": "deployed",
        }

    supporting_files = {
        "README.md": _generate_readme(idea, state.get("scoring") or {}, backend_code),
        ".github/workflows/ci.yml": _generate_ci_yml(has_frontend=has_frontend),
        ".env.example": _generate_env_example(),
    }
    commit_sha = ""
    if github_full_name:
        push_result = await push_files(
            {"full_name": github_full_name},
            supporting_files,
            commit_message="Add project docs, CI workflow, and env example",
        )
        commit_sha = push_result.get("commit_sha", "")
    await _emit_step_complete(
        "git_push",
        "Repository push complete" if commit_sha else "Repository created; support commit metadata unavailable",
        config=config,
        github_repo=github_repo_url,
        commit_sha=commit_sha,
    )

    ci_result = {"status": "skipped"}
    repair_attempts = 0
    if github_full_name and commit_sha:
        await _emit_step_start("ci_test", "Running CI workflow", config=config, commit_sha=commit_sha)
        ci_result, all_files, repair_attempts = await _ci_repair_loop(
            github_full_name, commit_sha, all_files, max_retries=3, config=config
        )
        ci_status = ci_result.get("status", "skipped")
        if ci_status in {"passed", "skipped"}:
            await _emit_step_complete(
                "ci_test",
                "CI passed" if ci_status == "passed" else "CI skipped",
                config=config,
                ci_status=ci_status,
                ci_url=ci_result.get("url", ""),
                ci_repair_attempts=repair_attempts,
            )
        else:
            await _emit_step_error(
                "ci_test",
                "CI failed" if ci_status == "failed" else "CI timed out",
                config=config,
                ci_status=ci_status,
                ci_url=ci_result.get("url", ""),
                ci_repair_attempts=repair_attempts,
            )
    else:
        await _emit_step_complete(
            "ci_test",
            "CI skipped: no workflow commit available",
            config=config,
            ci_status="skipped",
        )

    ci_meta = {
        "ci_status": ci_result.get("status", "skipped"),
        "ci_url": ci_result.get("url", ""),
        "ci_repair_attempts": repair_attempts,
    }

    do_token = os.getenv("DIGITALOCEAN_API_TOKEN")
    if not do_token:
        if github_full_name:
            _set_repo_metadata(
                github_full_name,
                topics=["ai", "fastapi", "digitalocean", "vibedeploy", "hackathon", "llm"],
                homepage=github_repo_url,
            )
        await _emit_step_error("app_spec", "App Spec skipped: DigitalOcean token missing", config=config)
        result = await _local_fallback_deploy(app_name, all_files, github_repo_url, "do_token_missing")
        result["deploy_result"].update(ci_meta)
        return result

    await _emit_step_start("app_spec", "Generating App Platform specification", config=config)
    app_spec = build_app_spec(app_name, github_clone_url, has_frontend=has_frontend)
    await _emit_step_complete(
        "app_spec",
        "App Platform specification ready",
        config=config,
        has_frontend=has_frontend,
    )

    deploy_progress = {
        "build_started": False,
        "build_completed": False,
        "deploy_started": False,
        "deploy_completed": False,
    }

    async def _track_do_phase(phase_name: str) -> None:
        normalized = str(phase_name or "").upper()
        if "BUILD" in normalized:
            if not deploy_progress["build_started"]:
                deploy_progress["build_started"] = True
                await _emit_step_start("do_build", "DigitalOcean build started", config=config, do_phase=phase_name)
            return

        if "DEPLOY" in normalized:
            if not deploy_progress["build_started"]:
                deploy_progress["build_started"] = True
                await _emit_step_start("do_build", "DigitalOcean build started", config=config, do_phase=phase_name)
            if not deploy_progress["build_completed"]:
                deploy_progress["build_completed"] = True
                await _emit_step_complete("do_build", "DigitalOcean build complete", config=config, do_phase=phase_name)
            if not deploy_progress["deploy_started"]:
                deploy_progress["deploy_started"] = True
                await _emit_step_start("do_deploy", "DigitalOcean deploy started", config=config, do_phase=phase_name)
            return

        if normalized == "ACTIVE":
            if not deploy_progress["build_started"]:
                deploy_progress["build_started"] = True
                await _emit_step_start("do_build", "DigitalOcean build started", config=config, do_phase=phase_name)
            if not deploy_progress["build_completed"]:
                deploy_progress["build_completed"] = True
                await _emit_step_complete("do_build", "DigitalOcean build complete", config=config, do_phase=phase_name)
            if not deploy_progress["deploy_started"]:
                deploy_progress["deploy_started"] = True
                await _emit_step_start("do_deploy", "DigitalOcean deploy started", config=config, do_phase=phase_name)
            if not deploy_progress["deploy_completed"]:
                deploy_progress["deploy_completed"] = True
                await _emit_step_complete(
                    "do_deploy", "DigitalOcean deploy complete", config=config, do_phase=phase_name
                )

    await _emit_step_start("do_build", "Submitting App Platform build", config=config)
    deploy_progress["build_started"] = True
    deploy_result = await _deploy_with_capacity_retry(app_name, github_clone_url, app_spec)

    if deploy_result.get("status") == "error":
        logger.error(
            "[DEPLOYER] DO app creation failed: %s",
            deploy_result.get("error", "unknown"),
        )
        await _emit_step_error(
            "do_build",
            f"App Platform build submission failed: {deploy_result.get('error', 'unknown')}",
            config=config,
            error=deploy_result.get("error", "unknown"),
        )
        result = await _local_fallback_deploy(
            app_name,
            all_files,
            github_repo_url,
            f"do_deploy_failed: {deploy_result.get('error', 'DigitalOcean deployment failed')}",
            app_id=deploy_result.get("app_id", ""),
        )
        result["deploy_result"].update(ci_meta)
        return result

    app_id = deploy_result.get("app_id", "")
    live_url = ""
    deploy_repair_attempts = 0

    for attempt in range(3):
        live_url = await wait_for_deployment(app_id, on_phase_change=_track_do_phase) if app_id else ""
        if live_url:
            break

        await asyncio.sleep(15)
        error_logs = await get_deploy_error_logs(app_id)
        if not error_logs:
            logger.warning("[DEPLOYER] Deploy failed but no error logs available (attempt %d)", attempt + 1)
            break

        logger.warning("[DEPLOYER] Deploy attempt %d failed. Repairing from error logs.", attempt + 1)
        await _emit_step_start(
            "do_build",
            f"Deploy repair attempt {attempt + 1}/3",
            config=config,
            deploy_repair_attempt=attempt + 1,
        )

        fixed_files = await _repair_code_from_errors(all_files, error_logs)
        if fixed_files == all_files:
            logger.warning("[DEPLOYER] LLM could not fix deploy errors (attempt %d)", attempt + 1)
            break

        all_files = await _prepare_files_for_push(fixed_files)
        push_result = await push_files(
            {"full_name": github_full_name},
            all_files,
            commit_message=f"fix: deploy repair attempt {attempt + 1}",
        )
        if not push_result.get("commit_sha"):
            logger.warning("[DEPLOYER] Failed to push repair (attempt %d)", attempt + 1)
            break

        await asyncio.sleep(5)
        redeploy_result = await redeploy_app(app_id)
        if redeploy_result.get("status") == "error":
            logger.warning("[DEPLOYER] Redeploy trigger failed: %s", redeploy_result.get("error", ""))
            break

        await _emit_step_complete(
            "do_build",
            f"Deploy repair attempt {attempt + 1} — redeploying",
            config=config,
            deploy_repair_attempt=attempt + 1,
        )

        deploy_repair_attempts = attempt + 1

    ci_meta["deploy_repair_attempts"] = deploy_repair_attempts

    if not live_url:
        failed_node = (
            "do_deploy" if deploy_progress["deploy_started"] or deploy_progress["build_completed"] else "do_build"
        )
        await _emit_step_error(
            failed_node,
            "DigitalOcean did not produce a live URL",
            config=config,
            app_id=app_id,
            deploy_repair_attempts=deploy_repair_attempts,
        )
        result = await _local_fallback_deploy(
            app_name,
            all_files,
            github_repo_url,
            f"do_deploy_failed_after_{deploy_repair_attempts}_repairs",
            app_id=app_id,
        )
        result["deploy_result"].update(ci_meta)
        return result

    if not deploy_progress["build_completed"]:
        deploy_progress["build_completed"] = True
        await _emit_step_complete("do_build", "DigitalOcean build complete", config=config, app_id=app_id)
    if not deploy_progress["deploy_started"]:
        deploy_progress["deploy_started"] = True
        await _emit_step_start("do_deploy", "DigitalOcean deploy started", config=config, app_id=app_id)
    if not deploy_progress["deploy_completed"]:
        deploy_progress["deploy_completed"] = True
        await _emit_step_complete(
            "do_deploy", "DigitalOcean deploy complete", config=config, app_id=app_id, live_url=live_url
        )

    await _emit_step_start("verified", "Verifying live URL", config=config, live_url=live_url)
    url_verification = _verify_live_url(live_url)
    v_score = url_verification.get("verification_score", 0)
    v_verdict = url_verification.get("verification_verdict", "failed")

    if v_verdict == "verified":
        logger.info(
            "[DEPLOYER] Live URL verified (score=%d, verdict=%s): %s",
            v_score, v_verdict, live_url,
        )
        await _emit_step_complete(
            "verified",
            f"Live URL verified (score={v_score}/100)",
            config=config,
            live_url=live_url,
            verification_score=v_score,
            verification_verdict=v_verdict,
        )
    elif v_verdict == "partial":
        logger.warning(
            "[DEPLOYER] Live URL partially verified (score=%d, verdict=%s): %s",
            v_score, v_verdict, live_url,
        )
        await _emit_step_complete(
            "verified",
            f"Live URL partially verified (score={v_score}/100) — basic functionality works, some issues detected",
            config=config,
            live_url=live_url,
            verification_score=v_score,
            verification_verdict=v_verdict,
        )
    else:
        # verdict == "failed" (score < 50) — attempt repair
        logger.warning(
            "[DEPLOYER] Live URL verification FAILED (score=%d, verdict=%s): %s — attempting repair",
            v_score, v_verdict, live_url,
        )
        await _emit_step_error(
            "verified",
            f"Live URL verification failed (score={v_score}/100) — attempting repair",
            config=config,
            live_url=live_url,
            verification_score=v_score,
            verification_verdict=v_verdict,
        )

        # Build a diagnostic summary from the verification result for the repair LLM
        diag_lines = [f"Verification score: {v_score}/100 (verdict: {v_verdict})"]
        if not url_verification.get("root_ok"):
            diag_lines.append("CRITICAL: Root page did not return 200 or returned <100 bytes")
        if not url_verification.get("health_ok"):
            diag_lines.append("CRITICAL: /health endpoint did not return 200")
        cs = url_verification.get("content_signals", {})
        if not cs.get("has_title"):
            diag_lines.append("Missing: <title> tag in HTML")
        if not cs.get("has_semantic_html"):
            diag_lines.append("Missing: semantic HTML elements (h1, nav, main)")
        if not cs.get("has_interactive_elements"):
            diag_lines.append(f"Missing: interactive elements (only {cs.get('interactive_count', 0)} found, need >=3)")
        if cs.get("broken_images"):
            diag_lines.append(f"Broken images: {cs['broken_images'][:3]}")
        failed_eps = [
            k for k, v in url_verification.get("endpoint_results", {}).items()
            if not v.get("ok")
        ]
        if failed_eps:
            diag_lines.append(f"Failed API endpoints: {', '.join(failed_eps[:5])}")
        failed_assets = [
            k for k, v in url_verification.get("asset_checks", {}).items()
            if not v.get("ok")
        ]
        if failed_assets:
            diag_lines.append(f"Failed assets: {', '.join(failed_assets[:5])}")

        diag_summary = "\n".join(diag_lines)
        logger.info("[DEPLOYER] Verification diagnostics for repair:\n%s", diag_summary)

        # Attempt one repair cycle using the verification diagnostics
        error_logs = await get_deploy_error_logs(app_id) if app_id else ""
        combined_errors = f"=== Live URL Verification Failures ===\n{diag_summary}"
        if error_logs:
            combined_errors += f"\n\n=== Deploy Error Logs ===\n{error_logs}"

        fixed_files = await _repair_code_from_errors(all_files, combined_errors)
        if fixed_files != all_files:
            all_files = await _prepare_files_for_push(fixed_files)
            push_result = await push_files(
                {"full_name": github_full_name},
                all_files,
                commit_message="fix: repair from live URL verification failures",
            )
            if push_result.get("commit_sha") and app_id:
                await asyncio.sleep(5)
                redeploy_result = await redeploy_app(app_id)
                if redeploy_result.get("status") != "error":
                    repair_url = await wait_for_deployment(app_id)
                    if repair_url:
                        live_url = repair_url
                        # Re-verify after repair
                        url_verification = _verify_live_url(live_url)
                        v_score = url_verification.get("verification_score", 0)
                        v_verdict = url_verification.get("verification_verdict", "failed")
                        logger.info(
                            "[DEPLOYER] Post-repair verification: score=%d, verdict=%s",
                            v_score, v_verdict,
                        )

    homepage = live_url or github_repo_url
    if github_full_name:
        _set_repo_metadata(
            github_full_name,
            topics=["ai", "fastapi", "digitalocean", "vibedeploy", "hackathon", "llm"],
            homepage=homepage,
        )

    if live_url and github_full_name:
        updated_readme = _generate_readme(idea, state.get("scoring") or {}, backend_code, live_url=live_url)
        try:
            await push_files(
                {"full_name": github_full_name},
                {"README.md": updated_readme},
                commit_message="docs: add live demo URL to README",
            )
            logger.info("[DEPLOYER] README updated with live URL: %s", live_url)
        except Exception:
            logger.warning("[DEPLOYER] Failed to update README with live URL")

    return {
        "deploy_result": {
            "app_id": app_id,
            "live_url": live_url,
            "github_repo": github_repo_url,
            "status": "deployed",
            "frontend_files": frontend_file_count,
            "backend_files": backend_file_count,
            "url_verification": url_verification,
            "verification_score": v_score,
            "verification_verdict": v_verdict,
            **ci_meta,
        },
        "phase": "deployed",
    }


async def _deploy_with_capacity_retry(app_name: str, github_clone_url: str, app_spec: dict) -> dict:
    deploy_result = await deploy_to_digitalocean(github_clone_url, app_spec)
    cleanup_attempts = 0

    while _is_do_app_limit_error(deploy_result) and cleanup_attempts < 3:
        cleanup_result = await _reclaim_do_app_capacity(app_name)
        if cleanup_result.get("status") != "deleted":
            break
        cleanup_attempts += 1
        deploy_result = await deploy_to_digitalocean(github_clone_url, app_spec)

    return deploy_result


def _is_do_app_limit_error(deploy_result: dict) -> bool:
    return (
        deploy_result.get("status") == "error" and _DO_APP_LIMIT_ERROR_SNIPPET in deploy_result.get("error", "").lower()
    )


async def _reclaim_do_app_capacity(target_app_name: str) -> dict:
    apps = await list_apps()
    failed_candidates = []
    live_candidates = []

    for app in apps:
        app_id = app.get("id", "")
        name = app.get("spec", {}).get("name", "")
        live_url = app.get("live_url", "")
        created_at = app.get("created_at", "")
        active_phase = app.get("active_deployment", {}).get("phase", "")
        in_progress_phase = app.get("in_progress_deployment", {}).get("phase", "")
        phase = in_progress_phase or active_phase or "UNKNOWN"

        if not app_id or not name or name in {target_app_name, "vibedeploy"}:
            continue
        if in_progress_phase or phase in {"PENDING", "BUILDING", "DEPLOYING"}:
            continue
        candidate = {
            "id": app_id,
            "name": name,
            "created_at": created_at,
            "phase": phase,
            "live_url": live_url,
        }
        if live_url:
            live_candidates.append(candidate)
        else:
            failed_candidates.append(candidate)

    candidates = failed_candidates or live_candidates
    if not candidates:
        logger.warning("[DEPLOYER] DO app limit reached but no generated apps were eligible for deletion")
        return {"status": "no_candidate"}

    candidates.sort(key=lambda app: (app.get("created_at", ""), app.get("name", "")))
    candidate = candidates[0]
    candidate_kind = "failed" if not candidate.get("live_url") else "oldest live"
    logger.warning(
        "[DEPLOYER] Deleting %s DO app to free capacity: %s (%s, phase=%s)",
        candidate_kind,
        candidate["name"],
        candidate["id"],
        candidate["phase"],
    )
    delete_result = await delete_app(candidate["id"])
    if delete_result.get("status") == "deleted":
        await asyncio.sleep(10)
    return delete_result


_CI_REPAIR_PROMPT = """You are a CI/deploy repair engineer. Fix the failing code so the build and deployment succeed.

Rules:
- Only fix files that caused the failure. Do NOT rewrite working files.
- For Python: fix imports, dependency names in requirements.txt, syntax errors, Pydantic model errors.
- For Node/TypeScript: fix package.json deps, type errors, build errors.
- Return ONLY the corrected files as JSON: { "files": { "path": "content" } }
- If a file doesn't need changes, do NOT include it.
- Keep all existing functionality — minimal fixes only.

Common DO App Platform errors and fixes:
- "use client" missing: Any Next.js file using useState/useEffect/useRef/event handlers MUST start with "use client" as the first line.
- PydanticUserError: Simplify Pydantic model field annotations. Use basic types only. Avoid clashing field/type names.
- "container exited with non-zero": Check Python imports, missing modules, Pydantic/SQLAlchemy compatibility with Python 3.13.
- "Failed to compile" / "npm run build failed": Fix TypeScript errors, missing imports, incorrect module paths.
"""

_TS_NULLABILITY_ERROR_RE = re.compile(
    r"(?P<path>\.?/?[^\s:][^\n:]*):(?P<line>\d+):\d+\s*\nType error: "
    r"'(?P<variable>[A-Za-z_$][\w$]*)' is possibly '(?:null|undefined)'\.",
    re.MULTILINE,
)
_PYTHON_NAME_ERROR_RE = re.compile(
    r'File "(?P<path>[^"]+)", line (?P<line>\d+), in [^\n]+\n'
    r"(?P<source>[^\n]+)\n"
    r"\s*\^+\n"
    r"NameError: name '(?P<name>[A-Za-z_][\w]*)' is not defined",
    re.MULTILINE,
)
_SQLALCHEMY_CORE_SYMBOLS = {
    "Integer",
    "String",
    "Text",
    "Date",
    "DateTime",
    "Boolean",
    "Float",
    "JSON",
    "Numeric",
    "ForeignKey",
    "Column",
    "Index",
}
_PYDANTIC_FIELD_CLASH_RE = re.compile(r"(?P<field>[A-Za-z_][\w]*)\s*:\s*(?P<annotation>[A-Za-z_][\w]*)\s*=\s*Field\(")
_NEXT_METADATA_CLIENT_ERROR_RE = re.compile(r'export "metadata" from a component marked with "use client"')
_UNTERMINATED_STRING_ERROR_RE = re.compile(r"Unterminated string constant")
_DUPLICATE_SSLMODE_ERROR_RE = re.compile(r"invalid sslmode value", re.IGNORECASE)
_LAYOUT_LITERAL_COMPARISON_ERROR_RE = re.compile(
    r"(?P<path>\.?/?[^\s:][^\n:]*):(?P<line>\d+):\d+\s*\n"
    r"Type error: This comparison appears to be unintentional because the types "
    r"'(?P<current>[^']+)' and '(?P<other>[^']+)' have no overlap\.",
    re.MULTILINE,
)
_CLIENT_COMPONENT_SIGNAL_RE = re.compile(
    r"\b(useState|useEffect|useRef|useReducer|useTransition|useDeferredValue)\b|"
    r"\bstartTransition\b|"
    r"on[A-Z][A-Za-z]+\s*=|"
    r"\bdocument\.|\bwindow\.",
)
_FRONTEND_CODE_SUFFIXES = (".ts", ".tsx", ".js", ".jsx")


async def _ci_repair_loop(
    full_name: str,
    commit_sha: str,
    files: dict[str, str],
    max_retries: int = 3,
    config=None,
) -> tuple[dict, dict[str, str], int]:
    for attempt in range(1, max_retries + 1):
        ci_result = await wait_for_ci(full_name, commit_sha, timeout=180)

        if ci_result.get("status") == "passed":
            return ci_result, files, attempt - 1

        if ci_result.get("status") in ("timeout", "skipped"):
            return ci_result, files, attempt - 1

        error_logs = await get_ci_failure_logs(full_name, commit_sha)
        if not error_logs:
            return ci_result, files, attempt

        await _emit_step_start(
            "ci_test",
            f"CI repair attempt {attempt}/{max_retries}",
            config=config,
            ci_repair_attempt=attempt,
            max_retries=max_retries,
        )

        fixed_files = await _repair_code_from_errors(files, error_logs)
        if fixed_files == files:
            return ci_result, files, attempt

        files = await _prepare_files_for_push(fixed_files)
        push_result = await push_files(
            {"full_name": full_name},
            files,
            commit_message=f"fix: CI repair attempt {attempt}",
        )
        commit_sha = push_result.get("commit_sha", "")
        if not commit_sha:
            return ci_result, files, attempt

        if commit_sha:
            await _emit_step_complete(
                "ci_test",
                f"CI repair attempt {attempt} pushed — re-running CI",
                config=config,
                ci_repair_attempt=attempt,
                commit_sha=commit_sha,
            )

    final_ci = await wait_for_ci(full_name, commit_sha, timeout=180)
    return final_ci, files, max_retries


async def _repair_code_from_errors(files: dict[str, str], error_logs: str) -> dict[str, str]:
    from ..llm import MODEL_CONFIG, ainvoke_with_retry, content_to_str, get_llm, get_rate_limit_fallback_models

    deterministic_fixes = _apply_deterministic_repairs(files, error_logs)
    if deterministic_fixes != files:
        return deterministic_fixes

    repair_model = MODEL_CONFIG["ci_repair"]
    llm = get_llm(model=repair_model, temperature=0.1, max_tokens=8000)

    file_listing = "\n\n".join(
        f"=== {path} ===\n{content}" for path, content in sorted(files.items()) if isinstance(content, str)
    )

    try:
        response = await ainvoke_with_retry(
            llm,
            [
                {"role": "system", "content": _CI_REPAIR_PROMPT},
                {
                    "role": "user",
                    "content": f"CI ERROR LOG:\n{error_logs[:4000]}\n\nCURRENT FILES:\n{file_listing}",
                },
            ],
            fallback_models=get_rate_limit_fallback_models(repair_model),
        )
    except Exception:
        return files

    raw = content_to_str(response.content).strip()
    parsed = _parse_repair_json(raw)
    if not parsed:
        return files

    result = dict(files)
    for path, content in parsed.items():
        if isinstance(path, str) and isinstance(content, str):
            result[path] = content
    return result


def _apply_deterministic_repairs(files: dict[str, str], error_logs: str) -> dict[str, str]:
    repaired = _apply_typescript_nullability_repairs(files, error_logs)
    repaired = _apply_layout_literal_type_repairs(repaired, error_logs)
    repaired = _apply_missing_sqlalchemy_import_repairs(repaired, error_logs)
    repaired = _apply_duplicate_sslmode_repairs(repaired, error_logs)
    repaired = _apply_next_layout_boundary_repairs(repaired, error_logs)
    repaired = _apply_pydantic_field_annotation_repairs(repaired, error_logs)
    return repaired


def _apply_typescript_nullability_repairs(files: dict[str, str], error_logs: str) -> dict[str, str]:
    updated_files = dict(files)
    changed = False

    for match in _TS_NULLABILITY_ERROR_RE.finditer(error_logs):
        relative_path = match.group("path").lstrip("./")
        line_number = int(match.group("line"))
        variable_name = match.group("variable")

        candidate_paths = [relative_path]
        if relative_path.startswith("web/"):
            candidate_paths.append(relative_path[4:])
        else:
            candidate_paths.append(f"web/{relative_path}")

        for candidate_path in candidate_paths:
            content = updated_files.get(candidate_path)
            if not isinstance(content, str):
                continue

            lines = content.splitlines()
            if line_number < 1 or line_number > len(lines):
                continue

            line_index = line_number - 1
            original_line = lines[line_index]
            repaired_line = re.sub(
                rf"(?<![\w$]){re.escape(variable_name)}(?=(?:\.|\[))",
                f"{variable_name}!",
                original_line,
                count=1,
            )
            if repaired_line == original_line:
                continue

            lines[line_index] = repaired_line
            updated_files[candidate_path] = "\n".join(lines) + ("\n" if content.endswith("\n") else "")
            changed = True
            break

    return updated_files if changed else files


def _apply_missing_sqlalchemy_import_repairs(files: dict[str, str], error_logs: str) -> dict[str, str]:
    updated_files = dict(files)
    changed = False

    for match in _PYTHON_NAME_ERROR_RE.finditer(error_logs):
        missing_name = match.group("name")
        if missing_name not in _SQLALCHEMY_CORE_SYMBOLS:
            continue

        for candidate_path in _candidate_paths_from_error(match.group("path")):
            content = updated_files.get(candidate_path)
            if not isinstance(content, str):
                continue

            repaired_content = _add_sqlalchemy_import(content, missing_name)
            if repaired_content == content:
                continue

            updated_files[candidate_path] = repaired_content
            changed = True
            break

    return updated_files if changed else files


def _apply_layout_literal_type_repairs(files: dict[str, str], error_logs: str) -> dict[str, str]:
    updated_files = dict(files)
    changed = False

    for match in _LAYOUT_LITERAL_COMPARISON_ERROR_RE.finditer(error_logs):
        for candidate_path in _candidate_paths_from_error(match.group("path")):
            content = updated_files.get(candidate_path)
            if not isinstance(content, str) or "const LAYOUT" not in content:
                continue

            repaired_content, replacements = re.subn(
                r'const\s+LAYOUT\s*=\s*(["\'][^"\']+["\'])\s*;',
                r"const LAYOUT: string = \1;",
                content,
                count=1,
            )
            if not replacements or repaired_content == content:
                continue

            updated_files[candidate_path] = repaired_content
            changed = True
            break

    return updated_files if changed else files


def _candidate_paths_from_error(raw_path: str) -> list[str]:
    normalized_path = raw_path.replace("\\", "/").strip()
    if normalized_path.startswith("/workspace/"):
        normalized_path = normalized_path[len("/workspace/") :]
    normalized_path = normalized_path.lstrip("./")

    candidate_paths = [normalized_path]
    if normalized_path.startswith("web/"):
        candidate_paths.append(normalized_path[4:])
    else:
        candidate_paths.append(f"web/{normalized_path}")
    return candidate_paths


def _add_sqlalchemy_import(content: str, missing_name: str) -> str:
    multiline_import = re.search(r"from sqlalchemy import \(\n(?P<body>[\s\S]*?)\n\)", content)
    if multiline_import:
        body = multiline_import.group("body")
        if re.search(rf"(?<![\w$]){re.escape(missing_name)}(?![\w$])", body):
            return content
        start, end = multiline_import.span()
        updated_block = multiline_import.group(0).replace("\n)", f"    {missing_name},\n)")
        return content[:start] + updated_block + content[end:]

    single_line_import = re.search(r"from sqlalchemy import (?P<body>[^\n]+)", content)
    if not single_line_import:
        return content

    body = single_line_import.group("body")
    if re.search(rf"(?<![\w$]){re.escape(missing_name)}(?![\w$])", body):
        return content

    start, end = single_line_import.span()
    updated_line = f"from sqlalchemy import {body}, {missing_name}"
    return content[:start] + updated_line + content[end:]


def _apply_pydantic_field_annotation_repairs(files: dict[str, str], error_logs: str) -> dict[str, str]:
    if "PydanticUserError" not in error_logs or "type annotation" not in error_logs:
        return files

    updated_files = dict(files)
    changed = False
    current_path = ""

    for raw_line in error_logs.splitlines():
        file_match = re.search(r'File "(?P<path>[^"]+)", line \d+, in ', raw_line)
        if file_match:
            current_path = file_match.group("path")
            continue

        field_match = _PYDANTIC_FIELD_CLASH_RE.search(raw_line.strip())
        if not field_match or not current_path:
            continue

        field_name = field_match.group("field")
        annotation_name = field_match.group("annotation")
        if field_name != annotation_name:
            continue

        annotation_alias = f"{annotation_name}_type"

        for candidate_path in _candidate_paths_from_error(current_path):
            content = updated_files.get(candidate_path)
            if not isinstance(content, str):
                continue

            aliased_content, import_updated = _alias_imported_symbol(content, annotation_name, annotation_alias)
            if not import_updated and annotation_alias not in aliased_content:
                continue

            repaired_content = re.sub(
                rf"(^\s*{re.escape(field_name)}\s*:\s*){re.escape(annotation_name)}(\s*=\s*Field\()",
                rf"\1{annotation_alias}\2",
                aliased_content,
                count=1,
                flags=re.MULTILINE,
            )
            if repaired_content == content:
                continue

            updated_files[candidate_path] = repaired_content
            changed = True
            break

    return updated_files if changed else files


def _apply_next_layout_boundary_repairs(files: dict[str, str], error_logs: str) -> dict[str, str]:
    metadata_boundary_error = bool(_NEXT_METADATA_CLIENT_ERROR_RE.search(error_logs))
    unterminated_string_error = bool(_UNTERMINATED_STRING_ERROR_RE.search(error_logs))

    if not metadata_boundary_error and not unterminated_string_error:
        return files

    updated_files = dict(files)
    changed = False
    layout_suffixes = ("src/app/layout.tsx", "src/app/layout.jsx", "app/layout.tsx", "app/layout.jsx")

    for path, content in files.items():
        if not path.endswith(layout_suffixes) and "use client" not in content:
            continue

        repaired_content = _canonicalize_use_client_directive(content)

        if (
            metadata_boundary_error
            and path.endswith(layout_suffixes)
            and ("export const metadata" in repaired_content or "generateMetadata" in repaired_content)
        ):
            repaired_content = re.sub(r'^\s*"use client";\n+', "", repaired_content, count=1)

        if repaired_content == content:
            continue

        updated_files[path] = repaired_content
        changed = True

    return updated_files if changed else files


def _apply_duplicate_sslmode_repairs(files: dict[str, str], error_logs: str) -> dict[str, str]:
    if not _DUPLICATE_SSLMODE_ERROR_RE.search(error_logs):
        return files

    updated_files = dict(files)
    changed = False
    guard_pattern = re.compile(
        r'if\s+not\s+_raw_url\.startswith\("sqlite"\)\s+and\s+"localhost"\s+not\s+in\s+_raw_url\s+and\s+"127\.0\.0\.1"\s+not\s+in\s+_raw_url\s*:',
        flags=re.MULTILINE,
    )
    replacement = (
        "if (\n"
        '    not _raw_url.startswith("sqlite")\n'
        '    and "localhost" not in _raw_url\n'
        '    and "127.0.0.1" not in _raw_url\n'
        '    and "sslmode=" not in _raw_url.lower()\n'
        "):"
    )

    for path, content in files.items():
        if not path.endswith(".py") or "_raw_url" not in content or "sslmode=require" not in content:
            continue
        repaired_content = guard_pattern.sub(replacement, content)
        if repaired_content == content:
            continue
        updated_files[path] = repaired_content
        changed = True

    return updated_files if changed else files


def _canonicalize_use_client_directive(content: str) -> str:
    lines = content.splitlines()
    for index, line in enumerate(lines):
        stripped = line.strip()
        if not stripped:
            continue
        if "use client" not in stripped:
            return content
        normalized = stripped.rstrip(";")
        normalized = normalized.replace('"', "").replace("'", "").strip()
        if normalized != "use client":
            return content
        lines[index] = '"use client";'
        updated = "\n".join(lines)
        if content.endswith("\n"):
            updated += "\n"
        return updated
    return content


def _alias_imported_symbol(content: str, symbol: str, alias: str) -> tuple[str, bool]:
    import_pattern = re.compile(r"^(from [\w\.]+ import )(?P<body>[^\n]+)$", re.MULTILINE)

    for match in import_pattern.finditer(content):
        body = match.group("body")
        items = [item.strip() for item in body.split(",")]
        if alias in items or f"{symbol} as {alias}" in items:
            return content, True
        if symbol not in items:
            continue

        updated_items = [f"{symbol} as {alias}" if item == symbol else item for item in items]
        updated_line = f"{match.group(1)}{', '.join(updated_items)}"
        return content[: match.start()] + updated_line + content[match.end() :], True

    return content, False


def _parse_repair_json(raw: str) -> dict[str, str] | None:
    if raw.startswith("```"):
        raw = re.sub(r"^```(?:json)?\n?", "", raw)
        raw = re.sub(r"\n?```$", "", raw)

    try:
        data = json.loads(raw)
    except json.JSONDecodeError:
        match = re.search(r"\{[\s\S]*\}", raw)
        if not match:
            return None
        try:
            data = json.loads(match.group())
        except json.JSONDecodeError:
            return None

    if isinstance(data, dict) and "files" in data:
        return data["files"] if isinstance(data["files"], dict) else None
    return data if isinstance(data, dict) else None


async def _local_fallback_deploy(
    app_name: str,
    files: dict[str, str],
    github_repo_url: str,
    reason: str,
    app_id: str = "",
) -> dict:
    base_dir = Path("/tmp/vibedeploy-apps") / _sanitize_app_name(app_name)
    _write_local_files(base_dir, files)

    backend_port = _find_free_port(start_port=9100)
    frontend_port = _find_free_port(start_port=backend_port + 1)

    web_dir = base_dir / "web"
    package_json_path = web_dir / "package.json"
    backend_main = base_dir / "main.py"
    backend_ready = False
    if backend_main.exists():
        backend_ready = await _spawn_local_backend_runtime(base_dir, backend_port)

    local_backend_url = f"http://127.0.0.1:{backend_port}"
    local_frontend_url = f"http://127.0.0.1:{frontend_port}"

    if package_json_path.exists():
        (web_dir / ".env.local").write_text(f"NEXT_PUBLIC_API_URL={local_backend_url}\n", encoding="utf-8")
        frontend_install = (
            ["npm", "ci"] if _has_usable_package_lock_file(web_dir / "package-lock.json") else ["npm", "install"]
        )
        await _run_foreground_command(frontend_install, web_dir)
        await _spawn_background_process(["npm", "run", "dev", "--", "--port", str(frontend_port)], web_dir)

    frontend_ready = await _wait_for_http_service(local_frontend_url, require_success=True)
    if not backend_ready:
        backend_ready = await _wait_for_http_service(local_backend_url, require_success=False)
    status = "local_running" if frontend_ready else "local_error"

    return {
        "deploy_result": {
            "app_id": app_id,
            "live_url": "",
            "github_repo": github_repo_url,
            "status": status,
            "local_reason": reason,
            "local_app_dir": str(base_dir),
            "local_url": local_frontend_url,
            "local_backend_url": local_backend_url,
            "local_frontend_url": local_frontend_url,
            "local_backend_ready": backend_ready,
            "local_frontend_ready": frontend_ready,
        },
        "phase": "deployed",
    }


async def _spawn_local_backend_runtime(base_dir: Path, backend_port: int) -> bool:
    if shutil.which("docker") and os.getenv("VIBEDEPLOY_LOCAL_RUNTIME_USE_DOCKER", "1").strip().lower() not in {
        "0",
        "false",
        "no",
        "off",
    }:
        return await _spawn_local_backend_runtime_docker(base_dir, backend_port)

    requirements_path = base_dir / "requirements.txt"
    if requirements_path.exists():
        await _run_foreground_command(["pip", "install", "-r", "requirements.txt"], base_dir)

    await _spawn_background_process(
        ["uvicorn", "main:app", "--host", "127.0.0.1", "--port", str(backend_port)],
        base_dir,
    )
    return await _wait_for_http_service(f"http://127.0.0.1:{backend_port}", require_success=False)


async def _spawn_local_backend_runtime_docker(base_dir: Path, backend_port: int) -> bool:
    container_name = f"vibedeploy-local-{uuid.uuid4().hex[:12]}"
    cmd = [
        "docker",
        "run",
        "-d",
        "--rm",
        "--name",
        container_name,
        "-p",
        f"{backend_port}:8080",
        "-v",
        f"{base_dir}:/app",
        "-w",
        "/app",
        "python:3.12-slim",
        "sh",
        "-lc",
        "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8080",
    ]
    started = await _run_foreground_command(cmd, base_dir)
    if not started:
        return False
    return await _wait_for_http_service(f"http://127.0.0.1:{backend_port}", require_success=False)


def _write_local_files(base_dir: Path, files: dict[str, str]) -> None:
    base_dir.mkdir(parents=True, exist_ok=True)
    for rel_path, content in files.items():
        if not isinstance(rel_path, str) or not isinstance(content, str):
            continue
        target_path = (base_dir / rel_path).resolve()
        if base_dir.resolve() not in target_path.parents and target_path != base_dir.resolve():
            continue
        target_path.parent.mkdir(parents=True, exist_ok=True)
        target_path.write_text(content, encoding="utf-8")


async def _prepare_files_for_push(files: dict[str, str]) -> dict[str, str]:
    prepared = _normalize_frontend_push_files(files)
    prepared = await _ensure_frontend_lockfile(prepared)
    return prepared


def _normalize_frontend_push_files(files: dict[str, str]) -> dict[str, str]:
    prepared: dict[str, str] = {}
    layout_suffixes = ("web/src/app/layout.tsx", "web/src/app/layout.jsx", "web/app/layout.tsx", "web/app/layout.jsx")

    for path, content in files.items():
        if not isinstance(path, str) or not isinstance(content, str):
            continue

        updated = content
        if path.startswith("web/") and path.endswith(_FRONTEND_CODE_SUFFIXES):
            updated = _canonicalize_use_client_directive(updated)
            stripped = updated.lstrip()
            if (
                _CLIENT_COMPONENT_SIGNAL_RE.search(updated)
                and not stripped.startswith('"use client"')
                and not stripped.startswith("'use client'")
            ):
                updated = f'"use client";\n\n{updated.lstrip()}'

            if path.endswith(layout_suffixes) and ("export const metadata" in updated or "generateMetadata" in updated):
                updated = re.sub(r'^\s*"use client";\n+', "", updated, count=1)

        prepared[path] = updated

    return prepared


async def _ensure_frontend_lockfile(files: dict[str, str]) -> dict[str, str]:
    package_json = files.get("web/package.json", "")
    if not isinstance(package_json, str) or not package_json.strip():
        return files

    npm_bin = shutil.which("npm")
    if not npm_bin:
        prepared = dict(files)
        prepared.pop("web/package-lock.json", None)
        logger.info("[DEPLOYER] npm not available; removing any LLM-generated lockfile to avoid npm ci mismatch")
        return prepared

    existing_lock = files.get("web/package-lock.json", "")
    if _has_usable_package_lock(existing_lock):
        return files

    package_lock = await _generate_package_lock(package_json)
    prepared = dict(files)
    if _has_usable_package_lock(package_lock):
        prepared["web/package-lock.json"] = package_lock
    else:
        prepared.pop("web/package-lock.json", None)
    return prepared


async def _generate_package_lock(package_json: str) -> str:
    npm_bin = shutil.which("npm")
    if not npm_bin:
        logger.warning("[DEPLOYER] npm not found; skipping package-lock generation")
        return ""

    with tempfile.TemporaryDirectory(prefix="vibedeploy-lock-") as temp_dir:
        workspace = Path(temp_dir)
        (workspace / "package.json").write_text(package_json, encoding="utf-8")

        process = await asyncio.create_subprocess_exec(
            npm_bin,
            "install",
            "--package-lock-only",
            "--ignore-scripts",
            "--no-audit",
            "--no-fund",
            cwd=str(workspace),
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, stderr = await process.communicate()
        if process.returncode != 0:
            error_output = (stderr or stdout).decode("utf-8", errors="replace")[-400:]
            logger.warning("[DEPLOYER] Failed to generate package-lock.json: %s", error_output)
            return ""

        lockfile_path = workspace / "package-lock.json"
        if not lockfile_path.exists():
            logger.warning("[DEPLOYER] npm completed without producing package-lock.json")
            return ""

        return lockfile_path.read_text(encoding="utf-8")


def _has_usable_package_lock(content: str) -> bool:
    if not isinstance(content, str) or not content.strip():
        return False

    try:
        parsed = json.loads(content)
    except json.JSONDecodeError:
        return False

    return isinstance(parsed, dict) and isinstance(parsed.get("lockfileVersion"), int)


def _has_usable_package_lock_file(lockfile_path: Path) -> bool:
    if not lockfile_path.exists():
        return False

    try:
        return _has_usable_package_lock(lockfile_path.read_text(encoding="utf-8"))
    except OSError:
        return False


async def _spawn_background_process(command: list[str], cwd: Path) -> None:
    try:
        await asyncio.create_subprocess_exec(
            *command,
            cwd=str(cwd),
            stdout=asyncio.subprocess.DEVNULL,
            stderr=asyncio.subprocess.DEVNULL,
            start_new_session=True,
        )
    except FileNotFoundError:
        logger.warning("[DEPLOYER] Binary not found: %s", command[0])


async def _run_foreground_command(command: list[str], cwd: Path) -> bool:
    try:
        process = await asyncio.create_subprocess_exec(
            *command,
            cwd=str(cwd),
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
    except FileNotFoundError:
        logger.warning("[DEPLOYER] Binary not found: %s", command[0])
        return False

    stdout, stderr = await process.communicate()
    if process.returncode != 0:
        output = (stderr or stdout or b"").decode("utf-8", errors="replace")[-500:]
        logger.warning("[DEPLOYER] Command failed (%s): %s", " ".join(command), output)
        return False
    return True


async def _wait_for_http_service(url: str, *, require_success: bool, timeout_seconds: float = 45.0) -> bool:
    deadline = time.monotonic() + timeout_seconds
    while time.monotonic() < deadline:
        try:
            req = request.Request(url, method="GET")
            with request.urlopen(req, timeout=3) as response:
                if require_success:
                    if 200 <= response.status < 400:
                        return True
                else:
                    return True
        except error.HTTPError as exc:
            if not require_success and exc.code < 500:
                return True
        except (error.URLError, TimeoutError, OSError):
            pass
        await asyncio.sleep(1)
    return False


def _find_free_port(start_port: int) -> int:
    for port in range(start_port, start_port + 200):
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
            sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
            if sock.connect_ex(("127.0.0.1", port)) != 0:
                return port
    return start_port


def _sanitize_app_name(app_name: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_-]", "-", app_name).strip("-") or "vibedeploy-app"


def _ensure_unique_backend_table_prefix(files: dict[str, str], app_name: str) -> dict[str, str]:
    models_content = files.get("models.py", "")
    if not models_content or "TABLE_PREFIX" not in models_content:
        return files

    unique_prefix = _build_table_prefix(app_name)
    updated_models = re.sub(
        r'TABLE_PREFIX\s*=\s*["\'][^"\']+["\']',
        f'TABLE_PREFIX = "{unique_prefix}"',
        models_content,
        count=1,
    )
    if updated_models == models_content:
        return files

    updated_files = dict(files)
    updated_files["models.py"] = updated_models
    return updated_files


def _build_table_prefix(app_name: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "_", app_name.lower()).strip("_")
    return f"{slug[:24] or 'app'}_"


def _set_repo_metadata(full_name: str, topics: list[str], homepage: str) -> None:
    token = os.getenv("GITHUB_TOKEN")
    if not token or not full_name:
        return

    _github_api_request(
        method="PATCH",
        path=f"/repos/{full_name}",
        token=token,
        payload={"homepage": homepage},
    )
    _github_api_request(
        method="PUT",
        path=f"/repos/{full_name}/topics",
        token=token,
        payload={"names": topics},
    )


def _github_api_request(method: str, path: str, token: str, payload: dict) -> None:
    data = json.dumps(payload).encode("utf-8")
    req = request.Request(
        url=f"https://api.github.com{path}",
        data=data,
        method=method,
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
            "Content-Type": "application/json",
        },
    )
    try:
        with request.urlopen(req, timeout=15):
            pass
    except (error.HTTPError, error.URLError):
        return


def _generate_readme(idea: dict, scoring: dict, backend_code: dict, live_url: str = "") -> str:
    app_name = str(idea.get("name") or "vibeDeploy App")
    tagline = str(idea.get("tagline") or idea.get("problem") or "An application generated by vibeDeploy.")
    problem = str(idea.get("problem") or "No problem statement provided.")
    features = idea.get("features") or []
    if not isinstance(features, list):
        features = []

    tech_stack = idea.get("tech_stack") or {}
    if isinstance(tech_stack, list):
        tech_entries = [str(item) for item in tech_stack]
    elif isinstance(tech_stack, dict):
        tech_entries = [f"{k}: {v}" for k, v in tech_stack.items()]
    else:
        tech_entries = ["Backend: FastAPI", "Frontend: Next.js"]

    endpoints = _extract_api_endpoints(backend_code)
    endpoint_rows = "\n".join([f"| `{m}` | `{p}` |" for m, p in endpoints])
    if not endpoint_rows:
        endpoint_rows = "| `GET` | `/health` |"

    feature_lines = "\n".join([f"- {str(item)}" for item in features[:8]]) if features else ""
    tech_rows = "\n".join(
        [
            f"| {entry.split(':', 1)[0].strip()} | {entry.split(':', 1)[1].strip() if ':' in entry else entry} |"
            for entry in tech_entries
        ]
    )

    vibe_score = scoring.get("final_score")
    vibe_footer = f"Vibe Score: **{vibe_score}**" if vibe_score is not None else "Vibe Score: not available"

    github_org = os.getenv("GITHUB_ORG", "Two-Weeks-Team")

    live_demo_badge = ""
    if live_url:
        safe_url = live_url.replace("https://", "").replace("/", "%2F")
        live_demo_badge = (
            f'\n  <a href="{live_url}">'
            f'<img src="https://img.shields.io/badge/🔗_Live_Demo-{safe_url}-00C853?style=for-the-badge'
            f'&logo=digitalocean&logoColor=white" alt="Live Demo"/></a>'
        )

    return f"""# {app_name}

<p align="center">
  <a href="https://digitalocean.devpost.com/"><img src="https://img.shields.io/badge/DO_Gradient_AI_Hackathon_2026-0080FF?style=for-the-badge&logo=digitalocean&logoColor=white" alt="DO Hackathon"/></a>{live_demo_badge}
  <img src="https://img.shields.io/badge/AI-Powered-blueviolet?style=for-the-badge" alt="AI Powered"/>
  <img src="https://img.shields.io/badge/Python-3.12-3776AB?style=for-the-badge&logo=python&logoColor=white" alt="Python"/>
  <img src="https://img.shields.io/badge/FastAPI-0.115-009688?style=for-the-badge&logo=fastapi&logoColor=white" alt="FastAPI"/>
  <img src="https://img.shields.io/badge/Next.js-15-black?style=for-the-badge&logo=next.js" alt="Next.js"/>
  <img src="https://img.shields.io/badge/license-MIT-green?style=for-the-badge" alt="MIT"/>
</p>

> {tagline}

---

## Overview

{problem}

## Key Features

{feature_lines}

## Architecture

```
+------------------+        +---------------------+        +--------------------+
|                  |  HTTP   |                     |  HTTP  |                    |
|   Next.js 15     +------->+   FastAPI Backend    +------->+  DO Inference      |
|   Frontend       |  REST   |   Python 3.12       |  AI    |  (oss-120b model)  |
|   (port 3000)    +<-------+   (port 8000)        +<------+                    |
|                  |  JSON   |                     |  JSON  |                    |
+------------------+        +----------+----------+        +--------------------+
                                       |
                              +--------v--------+
                              |   PostgreSQL     |
                              |   (psycopg 3.2)  |
                              +-----------------+
```

## API Endpoints

| Method | Path |
|--------|------|
{endpoint_rows}

## Tech Stack

| Layer | Technology | Version |
|-------|-----------|---------|
| Runtime | Python | 3.12+ |
| Backend | FastAPI + uvicorn | 0.115.0 |
| Frontend | Next.js + React | 15.5.12 / 19.0.0 |
| Database | PostgreSQL + psycopg | 3.2.3 |
| AI | DO Serverless Inference | anthropic-claude-4.6-sonnet |
| Styling | Tailwind CSS | 3.4.17 |
{tech_rows}

## Quick Start

### Prerequisites

- Python 3.12+
- Node.js 22.x

### Run Locally

```bash
# Backend
python -m venv .venv && source .venv/bin/activate
pip install -r requirements.txt
cp .env.example .env   # fill in your keys
uvicorn main:app --reload --port 8000

# Frontend (new terminal)
cd web
npm install
npm run dev
```

## Environment Variables

Copy `.env.example` to `.env` and fill in values:

- `API_BASE_URL`
- `ENVIRONMENT`
- `LOG_LEVEL`

## Deploying to DigitalOcean

This app is designed for [DigitalOcean App Platform](https://www.digitalocean.com/products/app-platform):

```yaml
name: {app_name.lower().replace(" ", "-")}
services:
  - name: api
    github:
      repo: {github_org}/{app_name.lower().replace(" ", "-")}
      branch: master
    build_command: pip install -r requirements.txt
    run_command: uvicorn main:app --host 0.0.0.0 --port $PORT
    http_port: 8080
    instance_size_slug: apps-s-1vcpu-0.5gb
    envs:
      - key: GRADIENT_MODEL_ACCESS_KEY
        scope: RUN_TIME
        type: SECRET
      - key: DIGITALOCEAN_INFERENCE_KEY
        scope: RUN_TIME
        type: SECRET
static_sites:
  - name: web
    github:
      repo: {github_org}/{app_name.lower().replace(" ", "-")}
      branch: master
    source_dir: web
    build_command: if [ -s package-lock.json ]; then npm ci || npm install; else npm install; fi && npm run build
    output_dir: web/.next
```

---

<p align="center">
  Generated by <a href="https://github.com/{github_org}/vibeDeploy"><strong>vibeDeploy</strong></a> | {vibe_footer}
</p>
"""


def _extract_api_endpoints(backend_code: dict) -> list[tuple[str, str]]:
    endpoints: list[tuple[str, str]] = []
    route_pattern = re.compile(r"@app\.(get|post|put|patch|delete)\(\s*['\"]([^'\"]+)['\"]")

    for content in backend_code.values():
        if not isinstance(content, str):
            continue
        for method, path in route_pattern.findall(content):
            endpoint = (method.upper(), path)
            if endpoint not in endpoints:
                endpoints.append(endpoint)

    return endpoints


def _generate_ci_yml(has_frontend: bool = False) -> str:
    backend_job = """  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          allow-prereleases: true
      - name: Install backend dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt found, skipping"
          fi
      - name: Backend smoke test
        run: python -c "import ast; [ast.parse(open(f).read()) for f in __import__('glob').glob('*.py')]"
"""

    frontend_job = """
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install frontend dependencies
        run: |
          if [ -s package-lock.json ]; then
            npm ci || npm install
          elif [ -f package.json ]; then
            npm install
          else
            echo "No package.json found, skipping"
            exit 0
          fi
      - name: Build frontend
        run: |
          if [ -f package.json ]; then
            npm run build
          fi
"""

    yml = """name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
"""
    yml += backend_job
    if has_frontend:
        yml += frontend_job
    return yml


def _generate_env_example() -> str:
    return """GRADIENT_MODEL_ACCESS_KEY=your-do-model-access-key
DIGITALOCEAN_INFERENCE_KEY=your-do-model-access-key
DO_INFERENCE_MODEL=anthropic-claude-4.6-sonnet
DATABASE_URL=postgresql://user:pass@localhost:5432/myapp
NEXT_PUBLIC_API_BASE_URL=http://127.0.0.1:8000
"""


def _merge_files(frontend_code: dict, backend_code: dict) -> dict[str, str]:
    merged: dict[str, str] = {}

    for path, content in backend_code.items():
        if isinstance(path, str) and isinstance(content, str):
            merged[path] = content

    for path, content in frontend_code.items():
        if not isinstance(path, str) or not isinstance(content, str):
            continue

        normalized_path = path if path.startswith("web/") else f"web/{path}"
        merged[normalized_path] = content

    return merged


def _get_deploy_blocker(
    frontend_code: dict,
    backend_code: dict,
    blueprint: dict | None,
    code_eval_result: dict | None = None,
    selected_flagship: str = "",
    build_validation: dict | None = None,
    deploy_gate_result: dict | None = None,
) -> str | None:
    gate = deploy_gate_result or {}
    if gate.get("passed"):
        return None

    eval_result = code_eval_result or {}
    if _allow_flagship_local_fallback(eval_result, selected_flagship):
        return None
    if eval_result.get("deployment_blocked"):
        blockers = eval_result.get("blockers") or []
        if blockers:
            return str(blockers[0])
        return "code quality gates blocked deployment"
    if eval_result and not eval_result.get("passed", False):
        return "code evaluation did not pass"

    bv = build_validation or {}
    if bv and not bv.get("passed", True) and not bv.get("skipped", False):
        errors = bv.get("errors") or ["build validation failed"]
        return f"build validation failed: {errors[0]}"

    expected_frontend = (blueprint or {}).get("frontend_files") or {}
    expected_backend = (blueprint or {}).get("backend_files") or {}

    if expected_backend:
        missing_backend = [path for path in ("main.py", "requirements.txt") if path not in backend_code]
        if missing_backend:
            return f"missing backend files: {', '.join(missing_backend)}"
        if len(backend_code) < 2:
            return "backend bundle is too small to deploy"

    if expected_frontend:
        if "package.json" not in frontend_code:
            return "missing frontend package.json"
        frontend_source_files = [
            path
            for path in frontend_code
            if path.startswith("src/") or path.startswith("app/") or path.endswith((".tsx", ".ts", ".jsx", ".js"))
        ]
        if len(frontend_code) < 3 or not frontend_source_files:
            return "frontend bundle is too small to deploy"

    if not frontend_code and not backend_code:
        return "no generated code files were available"

    return None


def _allow_flagship_local_fallback(eval_result: dict, selected_flagship: str) -> bool:
    if not selected_flagship:
        return False
    blockers = [str(value).strip() for value in eval_result.get("blockers") or [] if str(value).strip()]
    if blockers != ["deterministic fallback scaffold detected"]:
        return False
    completeness = float(eval_result.get("completeness", 0) or 0)
    runnability = float(eval_result.get("runnability", 0) or 0)
    experience = float(eval_result.get("experience", 0) or 0)
    return completeness >= 95 and runnability >= 85 and experience >= 85


def _build_repo_name(idea: dict) -> str:
    base_name = idea.get("name") or idea.get("tagline") or "vibedeploy-app"
    slug = re.sub(r"[^a-zA-Z0-9\s-]", "", str(base_name)).strip().lower()
    slug = re.sub(r"[\s_]+", "-", slug)
    slug = re.sub(r"-+", "-", slug)
    slug = slug[:45].strip("-") or "vibedeploy-app"

    suffix = str(int(time.time()))[-6:]
    return f"{slug}-{suffix}"


def _verify_live_url(live_url: str) -> dict:
    """E2E-level verification of a deployed URL.

    Returns a dict containing:
      - root_ok, health_ok, root_bytes (legacy fields)
      - content_signals: detailed frontend quality signals
      - endpoint_results: per-endpoint probe results
      - asset_checks: CSS/JS asset accessibility results
      - verification_score: 0-100 composite quality score
      - verification_verdict: "verified" | "partial" | "failed"
    """
    base = live_url.rstrip("/")
    result: dict = {
        "root_ok": False,
        "health_ok": False,
        "root_bytes": 0,
        "endpoint_results": {},
        "asset_checks": {},
        "verification_score": 0,
        "verification_verdict": "failed",
    }
    score = 0
    root_html = ""

    # ── Phase 0: Wait for root + health with retries ──────────────────
    for _ in range(6):
        for path, key in [("/", "root"), ("/health", "health"), ("/api/health", "health")]:
            try:
                req = request.Request(
                    f"{base}{path}",
                    headers={"User-Agent": "vibeDeploy-verifier/1.0"},
                )
                with request.urlopen(req, timeout=15) as resp:
                    body = resp.read()
                    if key == "root":
                        result["root_ok"] = resp.status == 200 and len(body) > 100
                        result["root_bytes"] = max(result["root_bytes"], len(body))
                        if resp.status == 200:
                            root_html = body.decode("utf-8", errors="replace")
                    else:
                        result["health_ok"] = resp.status == 200
            except (error.HTTPError, error.URLError, OSError):
                continue
        if result["root_ok"] and result["health_ok"]:
            break
        time.sleep(10)

    # Score: root page loads (200, >100 bytes): +15
    if result["root_ok"]:
        score += 15
        logger.info("[DEPLOYER][VERIFY] Root page OK (%d bytes) → +15", result["root_bytes"])
    else:
        logger.warning("[DEPLOYER][VERIFY] Root page FAILED (bytes=%d)", result["root_bytes"])

    # Score: health endpoint: +10
    if result["health_ok"]:
        score += 10
        logger.info("[DEPLOYER][VERIFY] Health endpoint OK → +10")
    else:
        logger.warning("[DEPLOYER][VERIFY] Health endpoint FAILED")

    # ── Phase 1: Frontend rendering quality check ─────────────────────
    content_signals: dict = {
        "has_title": False,
        "has_components": False,
        "has_styles": False,
        "content_length_ok": False,
        "has_spa_framework": False,
        "has_semantic_html": False,
        "has_interactive_elements": False,
        "has_meta_tags": False,
        "broken_images": [],
        "interactive_count": 0,
        "semantic_elements": [],
    }

    if root_html:
        html_lower = root_html.lower()

        # Basic content signals
        content_signals["content_length_ok"] = len(root_html) > 500
        content_signals["has_title"] = bool(re.search(r"<title>[^<]{3,}</title>", root_html, re.IGNORECASE))
        content_signals["has_components"] = root_html.count("<div") >= 3 or root_html.count("<section") >= 2
        content_signals["has_styles"] = (
            "tailwind" in html_lower or "globals.css" in html_lower or "<style" in html_lower
            or bool(re.search(r'<link[^>]+\.css', root_html, re.IGNORECASE))
        )

        # Score: has title: +5
        if content_signals["has_title"]:
            score += 5
            logger.info("[DEPLOYER][VERIFY] Title tag present → +5")
        else:
            logger.warning("[DEPLOYER][VERIFY] Title tag MISSING")

        # Score: has styles: +5
        if content_signals["has_styles"]:
            score += 5
            logger.info("[DEPLOYER][VERIFY] Styles present → +5")
        else:
            logger.warning("[DEPLOYER][VERIFY] Styles MISSING")

        # SPA framework detection
        content_signals["has_spa_framework"] = any(
            marker in root_html
            for marker in ("__NEXT_DATA__", "__NUXT__", "window.__remixContext", "id=\"__next\"", "id=\"app\"")
        ) or bool(re.search(r'<script[^>]+src="[^"]*\.(bundle|chunk|app)\.[^"]*\.js"', root_html, re.IGNORECASE))

        # Semantic HTML check: h1, nav/navigation, main/article
        found_semantic = []
        if re.search(r"<h1[\s>]", html_lower):
            found_semantic.append("h1")
        if re.search(r"<nav[\s>]", html_lower):
            found_semantic.append("nav")
        if re.search(r"<main[\s>]", html_lower):
            found_semantic.append("main")
        if re.search(r"<article[\s>]", html_lower):
            found_semantic.append("article")
        if re.search(r"<header[\s>]", html_lower):
            found_semantic.append("header")
        if re.search(r"<footer[\s>]", html_lower):
            found_semantic.append("footer")
        content_signals["semantic_elements"] = found_semantic
        content_signals["has_semantic_html"] = len(found_semantic) >= 2

        # Score: has semantic HTML (h1, nav, main): +10
        if content_signals["has_semantic_html"]:
            score += 10
            logger.info("[DEPLOYER][VERIFY] Semantic HTML present (%s) → +10", ", ".join(found_semantic))
        else:
            logger.warning("[DEPLOYER][VERIFY] Semantic HTML insufficient (found: %s)", found_semantic)

        # Interactive elements: buttons, forms, links
        button_count = len(re.findall(r"<button[\s>]", html_lower))
        form_count = len(re.findall(r"<form[\s>]", html_lower))
        link_count = len(re.findall(r"<a\s+[^>]*href=", html_lower))
        input_count = len(re.findall(r"<input[\s>]", html_lower))
        interactive_total = button_count + form_count + link_count + input_count
        content_signals["interactive_count"] = interactive_total
        content_signals["has_interactive_elements"] = interactive_total >= 3

        # Score: has interactive elements (buttons, forms, links >= 3): +10
        if content_signals["has_interactive_elements"]:
            score += 10
            logger.info(
                "[DEPLOYER][VERIFY] Interactive elements: %d (buttons=%d, forms=%d, links=%d, inputs=%d) → +10",
                interactive_total, button_count, form_count, link_count, input_count,
            )
        else:
            logger.warning("[DEPLOYER][VERIFY] Interactive elements insufficient (%d found)", interactive_total)

        # Meta tags check (og:title, description)
        has_og_title = bool(re.search(r'<meta[^>]+property=["\']og:title["\']', root_html, re.IGNORECASE))
        has_description = bool(
            re.search(r'<meta[^>]+name=["\']description["\']', root_html, re.IGNORECASE)
            or re.search(r'<meta[^>]+property=["\']og:description["\']', root_html, re.IGNORECASE)
        )
        content_signals["has_meta_tags"] = has_og_title or has_description

        # Score: meta tags present: +5
        if content_signals["has_meta_tags"]:
            score += 5
            logger.info("[DEPLOYER][VERIFY] Meta tags present (og:title=%s, description=%s) → +5", has_og_title, has_description)
        else:
            logger.warning("[DEPLOYER][VERIFY] Meta tags MISSING")

        # Broken images check
        img_srcs = re.findall(r'<img[^>]+src=["\']([^"\']*)["\']', root_html, re.IGNORECASE)
        broken_imgs = [src for src in img_srcs if not src or src.strip() in ("", "#", "about:blank")]
        content_signals["broken_images"] = broken_imgs

        # Score: no broken images: +5
        if not broken_imgs:
            score += 5
            logger.info("[DEPLOYER][VERIFY] No broken images → +5")
        else:
            logger.warning("[DEPLOYER][VERIFY] Broken images found: %s", broken_imgs[:5])

    result["content_signals"] = content_signals

    # ── Phase 2: API response structure validation ────────────────────
    openapi_endpoints = _discover_endpoints_from_openapi(base)
    all_endpoints_ok = True
    all_responses_valid = True

    for ep in openapi_endpoints:
        ep_path = ep["path"]
        ep_method = ep["method"]
        probe = _probe_endpoint_deep(base, ep_path, ep_method)
        passed = probe["status"] is not None and probe["status"] < 500
        result["endpoint_results"][f"{ep_method} {ep_path}"] = probe

        if not passed:
            all_endpoints_ok = False
            logger.warning(
                "[DEPLOYER][VERIFY] Endpoint probe FAILED: %s %s → status=%s",
                ep_method, ep_path, probe["status"],
            )
        if not probe.get("valid_response"):
            all_responses_valid = False

    # Score: API endpoints all respond without 5xx: +15
    if openapi_endpoints:
        if all_endpoints_ok:
            score += 15
            logger.info("[DEPLOYER][VERIFY] All %d API endpoints respond without 5xx → +15", len(openapi_endpoints))
        else:
            logger.warning("[DEPLOYER][VERIFY] Some API endpoints returned 5xx errors")

        # Score: API responses have valid JSON with content: +10
        if all_responses_valid:
            score += 10
            logger.info("[DEPLOYER][VERIFY] All API responses have valid JSON content → +10")
        else:
            logger.warning("[DEPLOYER][VERIFY] Some API responses have empty/invalid JSON")
    else:
        # No OpenAPI endpoints discovered — award the API points if health is OK
        # (backend-only apps without OpenAPI still get partial credit)
        if result["health_ok"]:
            score += 15
            logger.info("[DEPLOYER][VERIFY] No OpenAPI endpoints; health OK grants API credit → +15")

    # ── Phase 3: Asset integrity check ────────────────────────────────
    if root_html:
        css_refs = re.findall(r'<link[^>]+href=["\']([^"\']+\.css[^"\']*)["\']', root_html, re.IGNORECASE)
        js_refs = re.findall(r'<script[^>]+src=["\']([^"\']+\.js[^"\']*)["\']', root_html, re.IGNORECASE)
        asset_refs = css_refs + js_refs

        assets_ok = True
        checked = 0
        # Limit to 10 assets to keep within time budget
        for asset_url in asset_refs[:10]:
            full_url = asset_url
            if asset_url.startswith("/"):
                full_url = f"{base}{asset_url}"
            elif not asset_url.startswith(("http://", "https://")):
                full_url = f"{base}/{asset_url}"

            # Skip external CDN assets (tailwindcss, google fonts, etc.) — they are not our problem
            if not full_url.startswith(base):
                continue

            try:
                asset_req = request.Request(full_url, method="HEAD", headers={"User-Agent": "vibeDeploy-verifier/1.0"})
                with request.urlopen(asset_req, timeout=10) as resp:
                    if resp.status != 200:
                        assets_ok = False
                        result["asset_checks"][asset_url] = {"status": resp.status, "ok": False}
                        logger.warning("[DEPLOYER][VERIFY] Asset NOT OK: %s → %d", asset_url, resp.status)
                    else:
                        result["asset_checks"][asset_url] = {"status": 200, "ok": True}
                        checked += 1
            except error.HTTPError as e:
                assets_ok = False
                result["asset_checks"][asset_url] = {"status": e.code, "ok": False}
                logger.warning("[DEPLOYER][VERIFY] Asset error: %s → %d", asset_url, e.code)
            except (error.URLError, OSError) as e:
                assets_ok = False
                result["asset_checks"][asset_url] = {"status": None, "ok": False, "error": str(e)[:100]}
                logger.warning("[DEPLOYER][VERIFY] Asset unreachable: %s → %s", asset_url, e)

        # Score: assets load correctly: +10
        if assets_ok:
            score += 10
            logger.info("[DEPLOYER][VERIFY] All %d checked assets load OK → +10", checked)
        else:
            logger.warning("[DEPLOYER][VERIFY] Some assets failed to load")

    # ── Phase 4: Compute final score and verdict ──────────────────────
    score = min(score, 100)
    result["verification_score"] = score

    if score >= 80:
        result["verification_verdict"] = "verified"
    elif score >= 50:
        result["verification_verdict"] = "partial"
    else:
        result["verification_verdict"] = "failed"

    logger.info(
        "[DEPLOYER][VERIFY] Final score: %d/100 → verdict=%s",
        score, result["verification_verdict"],
    )

    return result


def _discover_endpoints_from_openapi(base_url: str) -> list[dict]:
    try:
        req = request.Request(
            f"{base_url}/openapi.json",
            headers={"User-Agent": "vibeDeploy-verifier/1.0"},
        )
        with request.urlopen(req, timeout=10) as resp:
            spec = json.loads(resp.read())
    except (error.HTTPError, error.URLError, OSError, json.JSONDecodeError):
        return []

    endpoints = []
    for path, methods in spec.get("paths", {}).items():
        if path in ("/health", "/", "/docs", "/redoc", "/openapi.json"):
            continue
        for method in methods:
            if method.lower() in ("get", "post", "put", "patch", "delete"):
                endpoints.append({"path": path, "method": method.upper()})
    return endpoints


def _probe_endpoint(base_url: str, path: str, method: str) -> int | None:
    """Legacy probe — returns only status code. Kept for backward compatibility."""
    result = _probe_endpoint_deep(base_url, path, method)
    return result["status"]


def _probe_endpoint_deep(base_url: str, path: str, method: str) -> dict:
    """Enhanced endpoint probe returning status, content-type, and response validity.

    Returns a dict with:
      - status: HTTP status code or None
      - ok: True if status < 500
      - content_type: response Content-Type header
      - valid_response: True if response is valid JSON with meaningful content
      - response_preview: first 200 chars of response body (for debugging)
    """
    url = f"{base_url}{path}"
    probe_result: dict = {
        "status": None,
        "ok": False,
        "content_type": "",
        "valid_response": False,
        "response_preview": "",
    }
    try:
        if method == "GET":
            req = request.Request(url, headers={"User-Agent": "vibeDeploy-verifier/1.0"})
        else:
            req = request.Request(
                url,
                data=b"{}",
                method=method,
                headers={
                    "User-Agent": "vibeDeploy-verifier/1.0",
                    "Content-Type": "application/json",
                },
            )
        with request.urlopen(req, timeout=15) as resp:
            body = resp.read()
            probe_result["status"] = resp.status
            probe_result["ok"] = resp.status < 500
            probe_result["content_type"] = resp.headers.get("Content-Type", "")

            body_text = body.decode("utf-8", errors="replace")
            probe_result["response_preview"] = body_text[:200]

            # Validate response has meaningful JSON content
            if "application/json" in probe_result["content_type"]:
                try:
                    parsed = json.loads(body_text)
                    # Check it is not an empty container or a generic error
                    if isinstance(parsed, dict):
                        # Empty dict or just a "detail" error is not valid content
                        if len(parsed) == 0:
                            probe_result["valid_response"] = False
                        elif list(parsed.keys()) == ["detail"] and "not found" in str(parsed.get("detail", "")).lower():
                            probe_result["valid_response"] = False
                        else:
                            probe_result["valid_response"] = True
                    elif isinstance(parsed, list):
                        # Empty list is not necessarily invalid (could be no data yet)
                        # but a list with items is clearly valid
                        probe_result["valid_response"] = len(parsed) > 0
                    else:
                        # Scalar JSON value — valid
                        probe_result["valid_response"] = True
                except (json.JSONDecodeError, ValueError):
                    probe_result["valid_response"] = False
            else:
                # Non-JSON response — valid if status is OK and has content
                probe_result["valid_response"] = resp.status < 400 and len(body) > 0

    except error.HTTPError as e:
        probe_result["status"] = e.code
        probe_result["ok"] = e.code < 500
        try:
            err_body = e.read().decode("utf-8", errors="replace")[:200]
            probe_result["response_preview"] = err_body
        except Exception:
            pass
    except (error.URLError, OSError):
        probe_result["status"] = None
        probe_result["ok"] = False

    return probe_result


async def _check_deploy_health(live_url: str, timeout: int = 30) -> dict:
    """Post-deploy health check on /health endpoint."""
    import httpx

    health_url = f"{live_url.rstrip('/')}/health"
    try:
        async with httpx.AsyncClient(timeout=timeout) as client:
            resp = await client.get(health_url)
            if resp.status_code == 200:
                return {"status": "healthy", "url": health_url, "status_code": 200}
            return {"status": "unhealthy", "url": health_url, "status_code": resp.status_code}
    except httpx.HTTPError as exc:
        return {"status": "unreachable", "url": health_url, "error": str(exc)[:200]}


def get_deploy_gate_status(state: dict) -> str:
    """Check if deployment should proceed based on build validation."""
    build_validation = state.get("build_validation") or {}
    if not build_validation.get("passed"):
        return "blocked"
    return "allowed"


def _inject_landing_page(main_py_content: str, idea: dict) -> str:
    app_name = idea.get("name", "App")
    tagline = idea.get("tagline", "Generated by vibeDeploy")
    features = idea.get("features", [])
    if not isinstance(features, list):
        features = []
    features_html = "".join(f"<li>{f}</li>" for f in features[:6])

    landing_route = (
        '''
from fastapi.responses import HTMLResponse

@app.get("/", response_class=HTMLResponse)
async def landing_page():
    return """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>'''
        + app_name
        + """</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-900 text-white min-h-screen flex items-center justify-center">
    <div class="max-w-2xl mx-auto text-center p-8">
        <h1 class="text-4xl font-bold mb-4">"""
        + app_name
        + """</h1>
        <p class="text-xl text-gray-300 mb-8">"""
        + tagline
        + """</p>
        <ul class="text-left text-gray-400 mb-8 space-y-2">"""
        + features_html
        + '''</ul>
        <div class="flex gap-4 justify-center">
            <a href="/docs" class="bg-blue-600 hover:bg-blue-700 px-6 py-3 rounded-lg font-medium">API Docs</a>
            <a href="/health" class="border border-gray-600 hover:border-gray-400 px-6 py-3 rounded-lg font-medium">Health Check</a>
        </div>
        <p class="text-gray-600 mt-12 text-sm">Powered by vibeDeploy &bull; DigitalOcean Gradient AI</p>
    </div>
</body>
</html>"""
'''
    )

    if "from fastapi import" in main_py_content:
        insert_after = main_py_content.find("\napp = ")
        if insert_after == -1:
            insert_after = main_py_content.find("\napp=")
        if insert_after != -1:
            line_end = main_py_content.find("\n", insert_after + 1)
            if line_end != -1:
                return main_py_content[: line_end + 1] + landing_route + main_py_content[line_end + 1 :]

    return main_py_content + "\n" + landing_route
